### ISSUE TITLE
bad user id snmp

### ISSUE THREAD

**Issue by ThejasK08** [kspviswa/py-playground#1]
mininet> h1 /usr/sbin/snmpd -Lsd -Lf /dev/null -u snmp -I -smux -p /var/run/snmpd.pid -c /etc/snmp/snmpd.conf
Bad user id: snmp
mininet>

**Comment by kspviswa** [comment]
Hello,
Not sure if you are still looking for a resolution, but if you do : in this example I already have a user named `snmp` that has privilege to run `snmpd` . So in your case, you can use whatever is the user that has access to. For more, refer [here](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-an-snmp-daemon-and-client-on-ubuntu-18-04) to understand how to create a dedicated user for snmpd.
